### ISSUE TITLE
Descriptive fields for route - not auto populating

### ISSUE THREAD

**Issue by mgallagher1985** [prowestgis/upp-wg#17]
The "Route Description", "Miles on County Roads", and "Total Route Length" fields show as "auto" on the application inputs spreadsheet, but they do not populate with values after a route is selected.

**Comment by lscharen** [comment]
The Road Class is not available in the current routing configuration.

The permit form was updated in commit cf12931598ff3c5df1eb78c040b9c82024489e0f to fill in the Route Description from the returned Name of the route and the total route length, as well.

Closing for now.
